services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    environment:
      - TZ=Australia/Sydney
      - WEBPASSWORD_FILE=/run/secrets/pihole_password
      - DNS1=1.1.1.1
      - DNS2=8.8.8.8
    secrets:
      - pihole_password
    volumes:
      - './pihole:/etc/pihole'
      - './dnsmasq.d:/etc/dnsmasq.d'
    network_mode: "host"
    cap_add:
      - NET_ADMIN

secrets:
  pihole_password:
    file: ./pihole_password.txt
